project:
  type: website
  output-dir: .output
  resources:
    - images/
    - css/
    - js/
    - www/
format: 
  revealjs:
    theme: [simple, css/deck.scss]
    logo: 'images/logo_compact_blue.svg'
    background-image: "images/background.png"
    background-size: "cover"
    include-after-body: js/_reveal.html
    margin: 0.05
    width: 1605
    height: 1050
    chalkboard: true
    transition: slide
    fragments: false
    incremental: true
filters: 
  - shinylive