project:
  type: website
  output-dir: .output
  render:
    - "**/*.qmd"
    - "!notes/**"
  resources:
    - images/
    - css/
    - js/
    - www/
    - notes/
engine: knitr
format: 
  revealjs:
    theme: [simple, css/deck.scss]
    logo: 'images/logo_compact_blue.svg'
    background-image: "images/background.png"
    background-size: "cover"
    include-after-body: _build/_reveal.html
    margin: 0.05
    width: 1605
    height: 1050
    chalkboard: true
    multiplex: false
    transition: slide
    fragments: false
    incremental: true
  html:
    code-fold: true
    code-summary: "Show code"
    toc: true
    toc-location: left
    toc-title: "Contents"
    toc-expand: true
filters: 
  - shinylive
  - include-code-files
  - _build/notes.lua