library(shiny)
library(bslib)
library(shinyjs)
library(ggplot2)
library(ggiraph)
library(munsell)

# Replace STYLE to add sidebar flex classes
STYLE <- HTML(
  "
  .btn{
    --bs-btn-padding-x: 0 !important;
  }
  .btnrow {
    display: flex;
    gap: 4px;
    align-items: stretch;
  }

  /* new: sidebar flex layout */
  .sidebar-flex {
    display: flex;
    flex-direction: column;
    height: 100%;
    gap: 8px;
  }
  .sidebar-flex .params {
    flex: 1 1 auto;
    overflow: auto;
    padding-bottom: 8px;
  }
  .sidebar-flex .simulation {
    flex: 0 0 auto;
    margin-top: auto; /* ensure it sits at the bottom */
  }

  /* ensure full-height behavior inside the built-in sidebar container */
  .sidebar > .sidebar-content {
    display: flex;
    flex-direction: column;
    height: 100%;
  }
"
)

ui <- page_sidebar(
  sidebar = sidebar(
    open = "always",
    width = 400,
    tags$style(STYLE),

    # wrap params and simulation into two flex units
    div(
      class = "sidebar-flex",
      # parameters area (scrollable)
      div(
        class = "params",
        h2("Probability Distributions"),

        selectizeInput(
          "distType",
          "Distribution Type",
          list(
            "Binomial",
            "Normal",
            "Uniform",
            "Exponential",
            "Poisson",
            "Beta",
            "Gamma"
          ),
          selected = "Binomial",
          multiple = FALSE
        ),

        # BINOMIAL
        conditionalPanel(
          condition = "input.distType == 'Binomial'",
          sliderInput(
            "successRate",
            "Success Rate",
            min = 0,
            max = 100,
            value = 50,
            step = 1,
            post = "%"
          ),
          numericInput(
            "trialCount",
            "Number of Trials",
            value = 10,
            min = 1,
            max = 1000
          ),
          p(
            tags$b("Generating Process:"),
            "A binomial distribution is generated by repeating a random event and counting how many successes occur."
          ),
          p(tags$i(
            "Examples: (1) flipping a coin 20 times and counting how many heads occur; (2) testing 50 light bulbs and counting how many are defective; (3) asking 10 survey respondents a yes/no question and counting how many answer 'yes.'"
          ))
        ),

        # NORMAL
        conditionalPanel(
          condition = "input.distType == 'Normal'",
          numericInput("mean", "Mean", value = 0),
          numericInput("sd", "Standard Deviation", value = 1, min = 0.0001),
          p(
            tags$b(
              "Generating Process:"
            ),
            "A normal distribution is generated when many small and independent random influences combine."
          ),
          p(tags$i(
            "Examples: (1) Measurement errors arising from many small sources of variation in a laboratory instrument. (2) Adult human heights within a large, homogeneous population. (3) Test scores on a well-designed exam taken by many students."
          ))
        ),

        # UNIFORM
        conditionalPanel(
          condition = "input.distType == 'Uniform'",
          numericInput("umin", "Minimum", value = 0),
          numericInput("umax", "Maximum", value = 1),
          p(
            tags$b(
              "Generating Process:"
            ),
            "A uniform distribution is generated when all values over a fixed interval have equal chance of arising."
          ),
          p(tags$i(
            "Examples: (1) Choosing a random card from a well-shuffled deck and recording its rank. (2) Rolling a six-sided die and recording the value. (3) Picking a number between 1 and 100 randomly."
          ))
        ),

        # EXPONENTIAL
        conditionalPanel(
          condition = "input.distType == 'Exponential'",
          numericInput("exp_rate", "Rate (λ)", value = 1, min = 1e-8),
          p(
            tags$b(
              "Generating Process:"
            ),
            "An exponential distribution is generated by measuring the waiting time until the next occurrence of an event that happens randomly at a constant average rate."
          ),
          p(tags$i(
            "Examples: (1) Time between incoming calls at a call center when calls occur randomly. (2) Time until an electronic device fails randomly. (3) Time until a cat is adopted from an animal shelter when all animals are adopted at a steady rate."
          ))
        ),

        # POISSON
        conditionalPanel(
          condition = "input.distType == 'Poisson'",
          numericInput("poisson_lambda", "Lambda (mean)", value = 1, min = 0),
          p(
            tags$b(
              "Generating Process:"
            ),
            "A Poisson distribution is generated by counting how many events occur within a fixed interval when events happen independently and randomly at a constant average rate."
          ),
          p(tags$i(
            "Examples: (1) Number of emails received in one hour. (2) Number of typing errors on a page of text. (3) Number of customers arriving at a store in a 10-minute period."
          ))
        ),

        # BETA
        conditionalPanel(
          condition = "input.distType == 'Beta'",
          numericInput("beta_alpha", "Alpha (α)", value = 2, min = 1e-8),
          numericInput("beta_beta", "Beta (β)", value = 2, min = 1e-8),
          p(
            tags$b(
              "Generating Process: A beta distribution is generated by modeling an unknown probability or proportion on the interval [0,1] using accumulated evidence about successes and failures, producing a flexible distribution over plausible values of that probability."
            ),
            ""
          ),
          p(tags$i(
            "Examples: (1) Modeling the true success probability of a coin after observing some number of heads and tails. (2) Modeling the fraction of time a machine is operational when past uptime and downtime observations inform the estimate. (3) Describing the proportion of a population with a certain trait when prior information and sample data are combined."
          ))
        ),

        # GAMMA
        conditionalPanel(
          condition = "input.distType == 'Gamma'",
          numericInput("gamma_shape", "Shape (k)", value = 2, min = 1e-8),
          numericInput("gamma_rate", "Rate (θ⁻¹)", value = 1, min = 1e-8),
          p(
            tags$b(
              "Generating Process:"
            ),
            "A gamma distribution is generated by measuring the total waiting time until a fixed number of independent events occur."
          ),
          p(tags$i(
            "Examples: (1) Total waiting time for a set number of calls to arrive at a call center with steady arrival intensity. (2) Total time until the 5th customer arrives at a service desk. (3) Time until a system experiences its 3rd failure when failures occur randomly at a constant rate."
          ))
        )
      ), # end params

      # simulation area pinned to bottom
      div(
        hr(),
        class = "simulation",
        h3("Simulation"),
        div(
          div(
            style = "padding-bottom: 6px;",
            class = "btnrow",
            actionButton("draw1", "Run 1", style = "flex: 1;"),
            actionButton("draw10", "×10", style = "flex: 1;"),
            actionButton("draw100", "×100", style = "flex: 1;"),
            actionButton("draw1000", "×1000", style = "flex: 1;")
          ),
          div(
            class = "btnrow",
            actionButton(
              "reset",
              "Reset",
              class = "btn btn-danger",
              style = "flex: 1;"
            )
          )
        )
      ) # end simulation
    ) # end sidebar-flex
  ),
  mainPanel(
    width = 12,
    girafeOutput("plot", width = "100%"),
    uiOutput("sim_list") # new: simulation results list (most recent highlighted)
  )
)

server <- function(input, output, session) {
  draws <- reactiveVal(numeric(0))

  observeEvent(
    list(
      input$trialCount,
      input$successRate,
      input$distType,
      input$mean,
      input$sd,
      input$umin,
      input$umax,
      input$exp_rate,
      input$poisson_lambda,
      input$beta_alpha,
      input$beta_beta,
      input$gamma_shape,
      input$gamma_rate
    ),
    {
      draws(numeric(0))
    },
    ignoreInit = TRUE
  )

  # helper: sanitize a positive numeric input
  safe_pos <- function(x, fallback = 1) {
    if (is.null(x) || !is.finite(x) || x <= 0) fallback else x
  }
  safe_nonneg <- function(x, fallback = 1) {
    if (is.null(x) || !is.finite(x) || x < 0) fallback else x
  }

  add_draws <- function(k) {
    new <- switch(
      input$distType,
      "Binomial" = rbinom(
        k,
        size = input$trialCount,
        prob = input$successRate / 100
      ),
      "Normal" = rnorm(k, mean = input$mean, sd = safe_pos(input$sd)),
      "Uniform" = runif(k, min = input$umin, max = input$umax),
      "Exponential" = rexp(k, rate = safe_pos(input$exp_rate)),
      "Poisson" = rpois(k, lambda = safe_nonneg(input$poisson_lambda)),
      "Beta" = rbeta(
        k,
        shape1 = safe_pos(input$beta_alpha),
        shape2 = safe_pos(input$beta_beta)
      ),
      "Gamma" = rgamma(
        k,
        shape = safe_pos(input$gamma_shape),
        rate = safe_pos(input$gamma_rate)
      ),
      numeric(0)
    )
    draws(c(draws(), new))
  }

  observeEvent(input$draw1, add_draws(1))
  observeEvent(input$draw10, add_draws(10))
  observeEvent(input$draw100, add_draws(100))
  observeEvent(input$draw1000, add_draws(1000))
  observeEvent(input$reset, {
    # clear simulated draws
    draws(numeric(0))

    # reset UI controls to their defaults (match UI definitions)
    updateSelectizeInput(session, "distType", selected = "Binomial")

    updateSliderInput(session, "successRate", value = 50)
    updateNumericInput(session, "trialCount", value = 10)

    updateNumericInput(session, "mean", value = 0)
    updateNumericInput(session, "sd", value = 1)

    updateNumericInput(session, "umin", value = 0)
    updateNumericInput(session, "umax", value = 1)

    updateNumericInput(session, "exp_rate", value = 1)
    updateNumericInput(session, "poisson_lambda", value = 1)

    updateNumericInput(session, "beta_alpha", value = 2)
    updateNumericInput(session, "beta_beta", value = 2)

    updateNumericInput(session, "gamma_shape", value = 2)
    updateNumericInput(session, "gamma_rate", value = 1)
  })

  output$plot <- renderGirafe({
    sim <- draws()

    # ---------- helpers ----------
    empty_plot <- function() girafe(ggplot(), width_svg = 12, height_svg = 8)

    # common theme
    base_theme <- theme_minimal() +
      theme(plot.margin = margin(10, 30, 30, 10))

    # ---------- spec builder ----------
    get_dist_spec <- function(sim) {
      dist <- input$distType

      # ---- BINOMIAL ----
      if (dist == "Binomial") {
        n <- input$trialCount
        p <- input$successRate / 100

        theory <- data.frame(
          x = 0:n,
          prob = dbinom(0:n, n, p)
        )

        list(
          type = "discrete",
          theory = theory,
          xlim = c(0, n),
          ymax = max(theory$prob),
          xlabel = "Number of successes",
          ylabel = "Probability",
          tooltip_theory = function(df) {
            paste0(
              "Success = ",
              df$x,
              " out of ",
              n,
              "<br>Probability = ",
              round(df$prob, 4)
            )
          }
        )
      } else if (dist == "Normal") {
        # ---- NORMAL ----
        mu <- input$mean
        sd <- safe_pos(input$sd)

        x_min <- mu - 4 * sd
        x_max <- mu + 4 * sd

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dnorm(xs, mu, sd)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Uniform") {
        # ---- UNIFORM ----
        a <- input$umin
        b <- input$umax
        if (b <= a) {
          return(NULL)
        }

        xs <- seq(a, b, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dunif(xs, a, b)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(a, b),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density",
          expand_mult = c(0, .85)
        )
      } else if (dist == "Exponential") {
        # ---- EXPONENTIAL ----
        rate <- safe_pos(input$exp_rate)

        x_min <- 0
        x_max <- qexp(.999, rate)

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dexp(xs, rate)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Poisson") {
        # ---- POISSON ----
        lambda <- safe_nonneg(input$poisson_lambda)

        x_max_theory <- ceiling(qpois(.999, lambda))
        x_max_sim <- if (length(sim)) {
          max(ceiling(sim), x_max_theory)
        } else {
          x_max_theory
        }
        xs <- 0:x_max_sim

        theory <- data.frame(
          x = xs,
          prob = dpois(xs, lambda)
        )

        list(
          type = "discrete",
          theory = theory,
          xlim = c(0, x_max_sim),
          ymax = max(theory$prob),
          xlabel = "k",
          ylabel = "Probability",
          tooltip_theory = function(df) {
            paste0("k = ", df$x, "<br>Probability = ", round(df$prob, 4))
          }
        )
      } else if (dist == "Beta") {
        # ---- BETA ----
        a <- safe_pos(input$beta_alpha)
        b <- safe_pos(input$beta_beta)

        xs <- seq(0, 1, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dbeta(xs, a, b)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(0, 1),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Gamma") {
        # ---- GAMMA ----
        shape <- safe_pos(input$gamma_shape)
        rate <- safe_pos(input$gamma_rate)

        x_min <- 0
        x_max <- qgamma(.999, shape, rate)

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dgamma(xs, shape, rate)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else {
        NULL
      }
    }

    # ---------- build plot ----------
    spec <- get_dist_spec(sim)
    if (is.null(spec)) {
      return(empty_plot())
    }

    g <- ggplot()

    # ---- simulated layer ----
    if (spec$type == "continuous") {
      if (length(sim) > 0) {
        g <- g +
          geom_histogram_interactive(
            data = data.frame(x = sim),
            aes(
              x = x,
              y = after_stat(density),
              tooltip = paste0("Count: ", after_stat(count)),
              data_id = after_stat(x)
            ),
            bins = 40,
            boundary = spec$xlim[1],
            fill = "steelblue",
            alpha = .6,
            color = "white",
            linewidth = .4
          )
      }

      g <- g +
        geom_line(
          data = spec$theory,
          aes(x = x, y = density),
          linewidth = 1
        )
    } else if (spec$type == "discrete") {
      # sim df
      df_sim <- if (length(sim) == 0) {
        data.frame(x = integer(), prob = numeric(), count = integer())
      } else {
        tab <- table(sim)
        data.frame(
          x = as.integer(names(tab)),
          count = as.integer(tab),
          prob = as.integer(tab) / sum(tab)
        )
      }

      g <- g +
        geom_col_interactive(
          data = df_sim,
          aes(
            x = x,
            y = prob,
            tooltip = paste0(
              "Count: ",
              count,
              " out of ",
              length(sim),
              "<br>Proportion: ",
              round(prob, 4)
            ),
            data_id = x
          ),
          fill = "steelblue",
          width = .8,
          alpha = .6
        ) +
        geom_line(
          data = spec$theory,
          aes(x = x, y = prob),
          linewidth = 1
        ) +
        geom_point_interactive(
          data = spec$theory,
          aes(
            x = x,
            y = prob,
            tooltip = spec$tooltip_theory(spec$theory),
            data_id = paste0("theory_", spec$theory$x)
          ),
          size = 3
        ) +
        scale_x_continuous(
          breaks = scales::breaks_pretty(n = 10, integer = TRUE)
        )
    }

    expand_mult <- spec$expand_mult %||% c(0, .25)

    g <- g +
      coord_cartesian(
        xlim = spec$xlim,
        ylim = c(0, spec$ymax),
        clip = "off"
      ) +
      scale_y_continuous(expand = expansion(mult = expand_mult)) +
      labs(x = spec$xlabel, y = spec$ylabel) +
      base_theme

    girafe(ggobj = g, width_svg = 12, height_svg = 8)
  })
  # compact single-line simulation values, most recent on the left in bold
  output$sim_list <- renderUI({
    sim_vals <- draws()

    # small formatter: integers as integers, others rounded to 2 decimals
    fmt_val <- function(x) {
      if (is.na(x)) {
        return("NA")
      }
      if (!is.numeric(x)) {
        return(as.character(x))
      }
      if (abs(x - round(x)) < 1e-8) {
        as.character(as.integer(round(x)))
      } else {
        sprintf("%.2f", round(x, 2))
      }
    }

    if (length(sim_vals) == 0) {
      return(tags$div(
        tags$div(
          "Simulation Results:",
          style = "font-weight:600; margin-bottom:4px;"
        ),
        tags$div("No simulations yet", style = "font-size:0.9em; color:#666;")
      ))
    }

    max_show <- 100L
    show_vals <- tail(sim_vals, max_show)
    show_vals_rev <- rev(show_vals) # most recent first (left)

    spans <- lapply(seq_along(show_vals_rev), function(i) {
      v <- show_vals_rev[i]
      txt <- fmt_val(v)
      if (i == 1L) {
        tags$span(
          txt,
          style = "font-weight:700; margin-right:10px; white-space:nowrap;"
        )
      } else {
        tags$span(
          txt,
          style = "color:#333; margin-right:10px; white-space:nowrap;"
        )
      }
    })

    tags$div(
      tags$div(
        "Recent simulations:",
        style = "font-weight:600; margin-bottom:4px;"
      ),
      tags$div(
        style = "font-size:0.9em; padding-top:2px; padding-bottom:6px; overflow-x:auto; white-space:nowrap;",
        spans
      )
    )
  })
}

shinyApp(ui, server)
