library(shiny)
library(bslib)
library(shinyjs)
library(ggplot2)
library(ggiraph)
library(munsell)

# Replace STYLE to add sidebar flex classes
STYLE <- HTML(
  "
  .btn{
    --bs-btn-padding-x: 0 !important;
  }
  .btnrow {
    display: flex;
    gap: 4px;
    align-items: stretch;
  }

  /* new: sidebar flex layout */
  .sidebar-flex {
    display: flex;
    flex-direction: column;
    height: 100%;
    gap: 8px;
  }
  .sidebar-flex .params {
    flex: 1 1 auto;
    overflow: auto;
    padding-bottom: 8px;
  }
  .sidebar-flex .simulation {
    flex: 0 0 auto;
    margin-top: auto; /* ensure it sits at the bottom */
  }

  /* ensure full-height behavior inside the built-in sidebar container */
  .sidebar > .sidebar-content {
    display: flex;
    flex-direction: column;
    height: 100%;
  }
"
)

ui <- page_sidebar(
  sidebar = sidebar(
    open = "always",
    width = 400,
    tags$style(STYLE),

    # wrap params and simulation into two flex units
    div(
      class = "sidebar-flex",
      # parameters area (scrollable)
      div(
        class = "params",
        h2("Probability Distributions"),

        selectizeInput(
          "distType",
          "Distribution Type",
          list(
            "Binomial",
            "Normal",
            "Uniform",
            "Exponential",
            "Poisson",
            "Beta",
            "Gamma"
          ),
          selected = "Binomial",
          multiple = FALSE
        ),

        # BINOMIAL
        conditionalPanel(
          condition = "input.distType == 'Binomial'",
          sliderInput(
            "successRate",
            "Success Rate",
            min = 0,
            max = 100,
            value = 50,
            step = 1,
            post = "%"
          ),
          numericInput(
            "trialCount",
            "Number of Trials",
            value = 10,
            min = 1,
            max = 1000
          ),
          p(
            tags$b("Generating Process:"),
            "A binomial distribution is generated by repeating a fixed number of independent trials, each with the same probability of success, and counting how many successes occur."
          ),
          p(tags$i(
            "Examples: (1) flipping a coin 20 times and counting how many heads occur; (2) testing 50 light bulbs and counting how many are defective; (3) asking 10 survey respondents a yes/no question and counting how many answer 'yes.'"
          ))
        ),

        # NORMAL
        conditionalPanel(
          condition = "input.distType == 'Normal'",
          numericInput("mean", "Mean", value = 0),
          numericInput("sd", "Standard Deviation", value = 1, min = 0.0001),
          p(
            tags$b(
              "Generating Process:"
            ),
            "A normal distribution is generated when many small, independent influences combine, producing values that cluster symmetrically around a mean with decreasing frequency farther from the center."
          ),
          p(tags$i(
            "Examples: (1) Measurement errors arising from many small sources of variation in a laboratory instrument. (2) Adult human heights within a large, homogeneous population. (3) Test scores on a well-designed exam taken by many students."
          ))
        ),

        # UNIFORM
        conditionalPanel(
          condition = "input.distType == 'Uniform'",
          numericInput("umin", "Minimum", value = 0),
          numericInput("umax", "Maximum", value = 1)
        ),

        # EXPONENTIAL
        conditionalPanel(
          condition = "input.distType == 'Exponential'",
          numericInput("exp_rate", "Rate (λ)", value = 1, min = 1e-8)
        ),

        # POISSON
        conditionalPanel(
          condition = "input.distType == 'Poisson'",
          numericInput("poisson_lambda", "Lambda (mean)", value = 1, min = 0)
        ),

        # BETA
        conditionalPanel(
          condition = "input.distType == 'Beta'",
          numericInput("beta_alpha", "Alpha (α)", value = 2, min = 1e-8),
          numericInput("beta_beta", "Beta (β)", value = 2, min = 1e-8)
        ),

        # GAMMA
        conditionalPanel(
          condition = "input.distType == 'Gamma'",
          numericInput("gamma_shape", "Shape (k)", value = 2, min = 1e-8),
          numericInput("gamma_rate", "Rate (θ⁻¹)", value = 1, min = 1e-8)
        )
      ), # end params

      # simulation area pinned to bottom
      div(
        hr(),
        class = "simulation",
        h3("Simulation"),
        div(
          div(
            style = "padding-bottom: 6px;",
            class = "btnrow",
            actionButton("draw1", "Run 1", style = "flex: 1;"),
            actionButton("draw10", "×10", style = "flex: 1;"),
            actionButton("draw100", "×100", style = "flex: 1;"),
            actionButton("draw1000", "×1000", style = "flex: 1;")
          ),
          div(
            class = "btnrow",
            actionButton(
              "reset",
              "Reset",
              class = "btn btn-danger",
              style = "flex: 1;"
            )
          )
        )
      ) # end simulation
    ) # end sidebar-flex
  ),
  mainPanel(
    width = 12,
    girafeOutput("plot", width = "100%"),
    uiOutput("sim_list") # new: simulation results list (most recent highlighted)
  )
)

server <- function(input, output, session) {
  draws <- reactiveVal(numeric(0))

  observeEvent(
    list(
      input$trialCount,
      input$successRate,
      input$distType,
      input$mean,
      input$sd,
      input$umin,
      input$umax,
      input$exp_rate,
      input$poisson_lambda,
      input$beta_alpha,
      input$beta_beta,
      input$gamma_shape,
      input$gamma_rate
    ),
    {
      draws(numeric(0))
    },
    ignoreInit = TRUE
  )

  add_draws <- function(k) {
    if (input$distType == "Binomial") {
      new <- rbinom(k, size = input$trialCount, prob = input$successRate / 100)
    } else if (input$distType == "Normal") {
      new <- rnorm(k, mean = input$mean, sd = input$sd)
    } else if (input$distType == "Uniform") {
      new <- runif(k, min = input$umin, max = input$umax)
    } else if (input$distType == "Exponential") {
      rate <- input$exp_rate
      if (!is.finite(rate) || rate <= 0) {
        rate <- 1
      }
      new <- rexp(k, rate = rate)
    } else if (input$distType == "Poisson") {
      lambda <- input$poisson_lambda
      if (!is.finite(lambda) || lambda < 0) {
        lambda <- 1
      }
      new <- rpois(k, lambda = lambda)
    } else if (input$distType == "Beta") {
      a <- input$beta_alpha
      b <- input$beta_beta
      if (!is.finite(a) || a <= 0) {
        a <- 1
      }
      if (!is.finite(b) || b <= 0) {
        b <- 1
      }
      new <- rbeta(k, shape1 = a, shape2 = b)
    } else if (input$distType == "Gamma") {
      shape <- input$gamma_shape
      rate <- input$gamma_rate
      if (!is.finite(shape) || shape <= 0) {
        shape <- 1
      }
      if (!is.finite(rate) || rate <= 0) {
        rate <- 1
      }
      new <- rgamma(k, shape = shape, rate = rate)
    } else {
      new <- numeric(0)
    }

    draws(c(draws(), new))
  }

  # helper: choose a sensible binwidth for histograms
  compute_binwidth <- function(
    sim,
    x_min,
    x_max,
    default_bins = 40,
    small_unique_thresh = 30
  ) {
    if (length(sim) == 0) {
      return((x_max - x_min) / default_bins)
    }
    ux <- sort(unique(sim))
    if (length(ux) == 1) {
      return((x_max - x_min) / default_bins)
    }
    # if values are integer-like, prefer a binwidth ~ 0.9 so integer bars don't overlap
    is_integer_like <- max(abs(ux - round(ux))) < 1e-8
    if (length(ux) <= small_unique_thresh) {
      min_sep <- min(diff(ux))
      if (is_integer_like) {
        # keep integer-like bars narrower (≈0.9) to avoid filling intermediate integers
        bw <- 0.9 * min(1, min_sep)
      } else {
        bw <- 0.9 * min_sep
      }
      if (!is.finite(bw) || bw <= 0) {
        bw <- (x_max - x_min) / default_bins
      }
      return(bw)
    }
    (x_max - x_min) / default_bins
  }

  # helper: compute a fixed column width for discrete-like values (or cap for continuous)
  compute_bar_width <- function(ux, binwidth, x_min, x_max) {
    if (length(ux) == 0) {
      return(binwidth * 0.9)
    }
    is_integer_like <- max(abs(ux - round(ux))) < 1e-8
    if (is_integer_like) {
      # fixed width for integer categories (prevents filling empty integer gaps)
      return(0.8)
    }
    # otherwise cap width to a reasonable fraction of the full range
    return(min(binwidth * 0.9, (x_max - x_min) / 20))
  }

  observeEvent(input$draw1, add_draws(1))
  observeEvent(input$draw10, add_draws(10))
  observeEvent(input$draw100, add_draws(100))
  observeEvent(input$draw1000, add_draws(1000))
  observeEvent(input$reset, {
    # clear simulated draws
    draws(numeric(0))

    # reset UI controls to their defaults (match UI definitions)
    updateSelectizeInput(session, "distType", selected = "Binomial")

    updateSliderInput(session, "successRate", value = 50)
    updateNumericInput(session, "trialCount", value = 10)

    updateNumericInput(session, "mean", value = 0)
    updateNumericInput(session, "sd", value = 1)

    updateNumericInput(session, "umin", value = 0)
    updateNumericInput(session, "umax", value = 1)

    updateNumericInput(session, "exp_rate", value = 1)
    updateNumericInput(session, "poisson_lambda", value = 1)

    updateNumericInput(session, "beta_alpha", value = 2)
    updateNumericInput(session, "beta_beta", value = 2)

    updateNumericInput(session, "gamma_shape", value = 2)
    updateNumericInput(session, "gamma_rate", value = 1)
  })

  output$plot <- renderGirafe({
    sim <- draws()

    # ---------- helpers ----------
    empty_plot <- function() girafe(ggplot(), width_svg = 12, height_svg = 8)

    # common theme
    base_theme <- theme_minimal() +
      theme(plot.margin = margin(10, 30, 30, 10))

    # ---------- spec builder ----------
    get_dist_spec <- function() {
      dist <- input$distType

      # ---- BINOMIAL ----
      if (dist == "Binomial") {
        n <- input$trialCount
        p <- input$successRate / 100

        theory <- data.frame(
          x = 0:n,
          prob = dbinom(0:n, n, p)
        )

        list(
          type = "discrete",
          theory = theory,
          xlim = c(0, n),
          ymax = max(theory$prob),
          xlabel = "Number of successes",
          ylabel = "Probability",
          tooltip_theory = function(df) {
            paste0(
              "Success = ",
              df$x,
              " out of ",
              n,
              "<br>Probability = ",
              round(df$prob, 4)
            )
          }
        )
      } else if (dist == "Normal") {
        # ---- NORMAL ----
        mu <- input$mean
        sd <- input$sd

        x_min <- mu - 4 * sd
        x_max <- mu + 4 * sd

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dnorm(xs, mu, sd)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Uniform") {
        # ---- UNIFORM ----
        a <- input$umin
        b <- input$umax
        if (b <= a) {
          return(NULL)
        }

        xs <- seq(a, b, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dunif(xs, a, b)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(a, b),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density",
          expand_mult = c(0, .85)
        )
      } else if (dist == "Exponential") {
        # ---- EXPONENTIAL ----
        rate <- input$exp_rate
        if (!is.finite(rate) || rate <= 0) {
          rate <- 1
        }

        x_min <- 0
        x_max <- qexp(.999, rate)

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dexp(xs, rate)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Poisson") {
        # ---- POISSON ----
        lambda <- input$poisson_lambda
        if (!is.finite(lambda) || lambda < 0) {
          lambda <- 1
        }

        x_max_theory <- ceiling(qpois(.999, lambda))
        x_max_sim <- if (length(sim)) {
          max(ceiling(sim), x_max_theory)
        } else {
          x_max_theory
        }
        xs <- 0:x_max_sim

        theory <- data.frame(
          x = xs,
          prob = dpois(xs, lambda)
        )

        list(
          type = "discrete",
          theory = theory,
          xlim = c(0, x_max_sim),
          ymax = max(theory$prob),
          xlabel = "k",
          ylabel = "Probability",
          tooltip_theory = function(df) {
            paste0("k = ", df$x, "<br>Probability = ", round(df$prob, 4))
          }
        )
      } else if (dist == "Beta") {
        # ---- BETA ----
        a <- input$beta_alpha
        b <- input$beta_beta
        if (!is.finite(a) || a <= 0) {
          a <- 1
        }
        if (!is.finite(b) || b <= 0) {
          b <- 1
        }

        xs <- seq(0, 1, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dbeta(xs, a, b)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(0, 1),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else if (dist == "Gamma") {
        # ---- GAMMA ----
        shape <- input$gamma_shape
        rate <- input$gamma_rate
        if (!is.finite(shape) || shape <= 0) {
          shape <- 1
        }
        if (!is.finite(rate) || rate <= 0) {
          rate <- 1
        }

        x_min <- 0
        x_max <- qgamma(.999, shape, rate)

        xs <- seq(x_min, x_max, length.out = 400)
        theory <- data.frame(
          x = xs,
          density = dgamma(xs, shape, rate)
        )

        list(
          type = "continuous",
          theory = theory,
          xlim = c(x_min, x_max),
          ymax = max(theory$density),
          xlabel = "Value",
          ylabel = "Density"
        )
      } else {
        NULL
      }
    }

    # ---------- build plot ----------
    spec <- get_dist_spec()
    if (is.null(spec)) {
      return(empty_plot())
    }

    g <- ggplot()

    # ---- simulated layer ----
    if (spec$type == "continuous") {
      if (length(sim) > 0) {
        g <- g +
          geom_histogram_interactive(
            data = data.frame(x = sim),
            aes(
              x = x,
              y = after_stat(density),
              tooltip = paste0("Count: ", after_stat(count)),
              data_id = after_stat(x)
            ),
            bins = 40,
            boundary = spec$xlim[1],
            fill = "steelblue",
            alpha = .6,
            color = "white",
            linewidth = .4
          )
      }

      g <- g +
        geom_line(
          data = spec$theory,
          aes(x = x, y = density),
          linewidth = 1
        )
    } else if (spec$type == "discrete") {
      # sim df
      df_sim <- if (length(sim) == 0) {
        data.frame(x = integer(), prob = numeric(), count = integer())
      } else {
        tab <- table(sim)
        data.frame(
          x = as.integer(names(tab)),
          count = as.integer(tab),
          prob = as.integer(tab) / sum(tab)
        )
      }

      g <- g +
        geom_col_interactive(
          data = df_sim,
          aes(
            x = x,
            y = prob,
            tooltip = paste0(
              "Count: ",
              count,
              " out of ",
              length(sim),
              "<br>Proportion: ",
              round(prob, 4)
            ),
            data_id = x
          ),
          fill = "steelblue",
          width = .8,
          alpha = .6
        ) +
        geom_line(
          data = spec$theory,
          aes(x = x, y = prob),
          linewidth = 1
        ) +
        geom_point_interactive(
          data = spec$theory,
          aes(
            x = x,
            y = prob,
            tooltip = spec$tooltip_theory(spec$theory),
            data_id = paste0("theory_", spec$theory$x)
          ),
          size = 3
        ) +
        scale_x_continuous(
          breaks = scales::breaks_pretty(n = 10, integer = TRUE)
        )
    }

    expand_mult <- spec$expand_mult %||% c(0, .25)

    g <- g +
      coord_cartesian(
        xlim = spec$xlim,
        ylim = c(0, spec$ymax),
        clip = "off"
      ) +
      scale_y_continuous(expand = expansion(mult = expand_mult)) +
      labs(x = spec$xlabel, y = spec$ylabel) +
      base_theme

    girafe(ggobj = g, width_svg = 12, height_svg = 9)
  })
  # compact single-line simulation values, most recent on the left in bold
  output$sim_list <- renderUI({
    sim_vals <- draws()

    # small formatter: integers as integers, others rounded to 2 decimals
    fmt_val <- function(x) {
      if (is.na(x)) {
        return("NA")
      }
      if (!is.numeric(x)) {
        return(as.character(x))
      }
      if (abs(x - round(x)) < 1e-8) {
        as.character(as.integer(round(x)))
      } else {
        sprintf("%.2f", round(x, 2))
      }
    }

    if (length(sim_vals) == 0) {
      return(tags$div(
        tags$div(
          "Simulation Results:",
          style = "font-weight:600; margin-bottom:4px;"
        ),
        tags$div("No simulations yet", style = "font-size:0.9em; color:#666;")
      ))
    }

    max_show <- 100L
    show_vals <- tail(sim_vals, max_show)
    show_vals_rev <- rev(show_vals) # most recent first (left)

    spans <- lapply(seq_along(show_vals_rev), function(i) {
      v <- show_vals_rev[i]
      txt <- fmt_val(v)
      if (i == 1L) {
        tags$span(
          txt,
          style = "font-weight:700; margin-right:10px; white-space:nowrap;"
        )
      } else {
        tags$span(
          txt,
          style = "color:#333; margin-right:10px; white-space:nowrap;"
        )
      }
    })

    tags$div(
      tags$div(
        "Recent simulations:",
        style = "font-weight:600; margin-bottom:4px;"
      ),
      tags$div(
        style = "font-size:0.9em; padding-top:2px; padding-bottom:6px; overflow-x:auto; white-space:nowrap;",
        spans
      )
    )
  })
}

shinyApp(ui, server)
